weekstart: 1
ampmtime: false
dotted: true
calafterschedule: false
addlasthalfhour: true

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 0.7cm
      bottom: 0.7cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.5
    quarterlylines: 36
    weeklylines: 11
    weeklyreflectgoals: 8
    weeklyreflectgood: 8
    weeklyreflectbad: 8
    dailytodos: 14
    dailynotes: 15
    dailypersonal: 6
    dailybottomhour: 7
    dailytophour: 23
    dailydiarygoals: 9
    dailydiarygrateful: 9
    dailydiarybest: 9
    dailydiaryimprove: 9
    dailydiarylog: 24
    todolinesintodopage: 10
    notesindexpages: 1
    notesonpage: 13
    notespagespernote: 10
    dotheightfull: 37
    dotnotesheightfull: 36
    dotwidthfull: 30
    dotwidthtwothirds: 20

  lengths:
    tabcolsep: 3.5pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 55pt
    notesindexcellheight: 1.7cm
    notesindexcellscale: 3.5
    headerresizebox: 6mm
    headersidequarterswidth: 4cm
    headersidemonthswidth: 14.5cm
    dailyspring: \textcolor{white}{.}

  colors:
    gray: gray
    lightgray: gray!50
